[package]
name = "fpipe"
version = "0.1.0"
authors = ["Alexandru Macovei <alexnmaco@gmail.com>"]
edition = "2018"
license = "MIT"

[dev-dependencies]
test_dir = "0.1.0"
assert_cmd = "1.0.1"
predicates = "*"

[dependencies]
structopt = "0.3.19"

[dependencies.tokio]
version = "0.3.0"
features = ["io-std", "io-util", "process", "rt"]

[profile.release]
lto = "fat"
