[package]
name = "fpipe"
version = "0.1.0"
authors = ["Alexandru Macovei <alexnmaco@gmail.com>"]
edition = "2018"
license = "MIT"

[dev-dependencies]
wait-timeout = "0.2.0"
test_dir = "0.1.0"
assert_cli = "0.6.3"

[dependencies]
structopt = "0.3.12"
